name: bulid/release Midi-K

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install rimraf & typescript
        run: npm i rimraf typescript -g

      - name: Build libnut-core
        working-directory: nutjs/libnut-core
        run: npm i && npm run build:release

      - name: Compile @nut-tree/shared
        working-directory: nutjs/shared
        run: npm i && npm run compile

      - name: Compile @nut-tree/provider-interfaces
        working-directory: nutjs/provider-interfaces
        run: npm i && npm run compile

      - name: Compile @nut-tree/clipboardy
        working-directory: nutjs/clipboardy
        run: npm i && npm run compile

      - name: Compile @nut-tree/libnut
        working-directory: nutjs/libnut
        run: npm i && npm run compile

      - name: Compile @nut-tree/nut.js
        working-directory: nutjs/nut.js
        run: npm i && npm run compile

      - name: Install Dependencies
        run: npm install

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/**/*-win.exe
            release/**/*-mac.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
