name: buid/release Midi-K

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/**/*-win.exe
            release/**/*-mac.dmg
          # files: |
          #   release/**/*.exe
          #   release/**/*.zip
          #   release/**/*.dmg
          #   release/**/*.AppImage
          #   release/**/*.snap
          #   release/**/*.deb
          #   release/**/*.rpm
          #   release/**/*.tar.gz
          #   release/**/*.yml
          #   release/**/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
